OTSapp/urls.py
from django.urls import path
from OTSapp.views import *
app_name = 'OTSapp'
urlpatterns = [
    path('', welcome),
    path('new-candidate',candidateRegistrationForm,name='Registration'),
    path('store-candidate',candidateRegistration,name='storeCandidate'),
    path('login',loginView,name='login'),
    path('home',candidateHome,name='home'),
    path('test-paper',testPaper,name='testPaper'),
    path('calculate-result',calculateTestResult,name='calculateTest'),
    path('test-history',TestResultHistory,name='testHistory'),
    path('result',showTestResult,name='result'),
    path('logout',logoutView,name='logout'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('OTSapp', include('OTSapp.urls')),
]

OTSapp/models.py
from django.db import models

# Create your models here.
class Candidate(models.Model):
    username = models.CharField(max_length=20, primary_key=True)
    password = models.CharField(null=False,max_length=20)
    name = models.CharField(max_length=20)
    test_attempted = models.IntegerField(default=0)
    points = models.FloatField(default=0.0)

class Questions(models.Model):
    qid = models.BigAutoField(primary_key=True, auto_created=True)
    que = models.TextField()
    a = models.CharField(max_length=255)
    b = models.CharField(max_length=255)
    c = models.CharField(max_length=255)
    d = models.CharField(max_length=255)
    ans = models.CharField(max_length=20)

class Result(models.Model):
    resultid = models.BigAutoField(primary_key=True, auto_created=True)
    username = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    time = models.TimeField(auto_now=True)
    attempt = models.IntegerField()
    right = models.IntegerField()
    wrong = models.IntegerField()
    points = models.FloatField(default=0)

OTSapp/views.py
from django.urls import reverse
from django.shortcuts import render#render HTMP templates
from django.http import HttpResponse,HttpResponseRedirect#return HTTP response
from .models import Candidate #Candidate model from the current application
from OTSapp.models import *#importing all models in this app
import random# used for generating random numbers or making random selections


def welcome(request):
    return render(request, 'welcome.html')

def candidateRegistrationForm(request):
    return render(request, 'registration_form.html')
    
def candidateRegistration(request):
    userStatus = 3  # Initialize userStatus and context
    context = {}
    
    if request.method == "POST":
        username = request.POST['username']
        # Check if the user already exists
        if(len( Candidate.objects.filter(username=username))):
            userStatus = 1
        else:
            candidate = Candidate()
            candidate.username = username
            candidate.password = request.POST['password']
            candidate.name = request.POST['name']
            candidate.save()
            userStatus = 2
    else:
        userStatus=3
    context={
            'userStatus':userStatus
    }
    
    res=render(request,'registration.html',context)
    return res
    
  
def loginView(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        candidate=Candidate.objects.filter(username=username,password=password)
        if len(candidate)==0:
            loginError='Invalid username or password '
            res=render(request, 'login.html',{'loginError':loginError})
        else:
            #login success
            request.session['username']=candidate[0].username
            request.session['name']=candidate[0].name 
            res = HttpResponseRedirect(reverse('OTSapp:home')) 
    else:        
       res=render(request, 'login.html')
    return res
def candidateHome(request):#getting error   for return request home.html ,will be fix  on next lecture
    if 'username' not in request.session.keys():
        res=render(request,"login.html")
    else:
        res=render(request,"home.html")
    return res
      
  
def testPaper(request):
    if 'name' not in request.session.keys():
        res=render(request,"login.html")
    #fetch question from database table
    n=int(request.GET['n'])
    question_pool=list(Questions.objects.all()) 
    random.shuffle(question_pool)
    questions_list=question_pool[:n]
    context={'questions':questions_list}
    res=render( request,'test_paper.html',context)
    return res
    
def calculateTestResult(request):
    if "name" not in request.session.keys():
        res= HttpResponseRedirect(reverse('OTSapp:login'))
        
    total_attempt=0
    total_right=0
    total_wrong=0
    qid_list=[]
    for k in request.POST:
        if k.startswith('qno'):
            qid_list.append(request.POST[k])

    
    for n in qid_list:
        question=Questions.objects.get(qid=n)
        try:
            if question.ans==request.POST['q'+str(n)]:
                total_right+=1
            else:
                total_wrong+=1
            total_attempt+=1
        except:
            pass
        else:
            points=(total_attempt-total_wrong)/len(qid_list)*10
    #store result in DB table
    result=Result()
    result.username=Candidate.objects.get(username=request.session['username'])
    result.attempt=total_attempt
    result.right=total_right
    result.wrong=total_wrong
    result.point=points
    result.save()
    #update Candidate table
    candidate=Candidate.objects.get(username=request.session['username'])
    candidate.test_attempted=1
    candidate.points=(candidate.points*(candidate.test_attempted-1)+points)/candidate.test_attempted
    candidate.save()
    return HttpResponseRedirect(reverse('OTSapp:result'))
def TestResultHistory(request): 
    if "name" not in request.session.keys():
        res= HttpResponseRedirect(reverse('OTSapp:login'))
    candidate=Candidate.objects.filter(username=request.session['username'])
    results=Result.objects.filter(username_id=candidate[0].username)
    context={'candidate_info':candidate[0],'result':results}
    res=render(request,'candidate_history.html',context)
    return res
    
    
def showTestResult(request):
    if "name" not in request.session.keys():
        res= HttpResponseRedirect(reverse('OTSapp:login'))
    #fetch latest result from result table
    result=Result.objects.filter(resultid=Result.objects.latest('date','time').resultid,  username_id=request.session['username'])
    context={'result':result}
    res=render(request,'show_result.html',context)
    return res
def logoutView(request):
    if 'name'  in request.session.keys():
        del request.session['username']
        del request.session['name']
    res=render(request,"login.html")
    return res

OTSapp/templates/candidate_history.html
{% extends 'main.html' %}

{% block tittle %}
Candidate  result history
{% endblock %}

{% block top %} 
<a  href="{%url 'OTSapp:home'%}" style="color:red;">Sign up</a>
<br>
<br>
<a href="{%url 'OTSapp:logout'%}" style="color:green;">Login</a>
{%endblock%}

{% block content %}
<h1>Your Report card</h1>
<p><b>{{candidate_info.name}} ,</b>you have attempted in total {{candidate_info.test_attempted}} 
    tests and you have scored {{candidate_info.points}} out of  scale 10</p>
<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>right</th>
        <th>wrong</th>
        <th>points</th>
    </tr>
    {% for r in result%}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
    {% endfor %}
        
    </tr>
</Table>

{%endblock%}
 
 

OTSapp/templates/home.html
{% extends 'main.html' %}

{% block tittle %}
OTS- Candidate Home page
{% endblock %}

{% block top %} 
<a href="{%url 'OTSapp:logout'%}">Logout</a>

{%endblock%}

{% block content %}
<h1>Welcome {{request.session.name}}  to your Home page </h1>
<div class="button-link">
    <a href="{%url 'OTSapp:testPaper'%}?n=1">test of 1 Questions</a>
</div>
<div class="button-link">
    <a href="{%url 'OTSapp:testPaper'%}?n=2">test of 2 Questions</a>
</div>
<div class="button-link">
    <a href="{%url 'OTSapp:testPaper'%}?n=3">test of 3 Questions</a>
</div>
<div class="button-link">
    <a href="{%url 'OTSapp:testHistory'%}">Test History</a>
</div>
{%endblock%}

OTSapp/templates/login.html
{% extends 'main.html' %}

{% block tittle %}
OTS login form
{% endblock %}

{% block top %} 
<span>
    <a href="{%url 'OTSapp:Registration'%}">Sign up</a>
</span><br>

{%endblock%}

{% block content %}
<div class="all-forms">
    {% if loginError %}
        <div  id="error">{{loginError}}</div>
    {% endif %}    
    <form action="{% url 'OTSapp:login'%}"  method="POST">
        {%csrf_token%}
        <div class="form-unit">
            <label for="username">Username</label>
            <input type="text" name="username"  required>
            <label for="password">Password</label>
            <input type="password" name="password" required>

        </div>
        <div class="form-unit">
            <input type="submit" value="login">
            <input type="reset" value="clear">
        </div>

    </form>
    New user <a href="{%url 'OTSapp:Registration'%}">Click here</a>

</div>
{%endblock%}

OTSapp/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block tittle %}{% endblock %}</title>
    <link rel="stylesheet" href="{%static 'theme.css'%}">
    <link rel="stylesheet" href="{%static 'formstyle.css'%}">
    <link rel="stylesheet" href="{%static 'buttonstyle.css'%}">
</head>
<body>
    <div class="top">
        <div class="sitename"><h1>Online Testing System</h1></div>
        <div class="menu">
            {% block top %}{% endblock %}
        </div>    
    </div>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    
</body> 
    

</html>

OTSapp/templates/registration.html
{% extends 'main.html' %}

{% block tittle %}
OTS Registration status
{% endblock %}

{% block top %} 
<a href="{%url 'OTSapp:Registration'%}">Sign up</a>
<br>
<a href="{%url 'OTSapp:login'%}">Login</a>
{%endblock%}

{% block content %}
{% if userStatus == 1%}
    <div class="userStatus">
        Sorry, username already exist, please try again different username 
        <a href="{%url 'OTSapp:Registration'%}">back to Registration form</a>
    </div>
{% elif  userStatus == 2%}   
<div class="userStatus">
    Congratulations , user created successfully
    <a href="{%url 'OTSapp:login'%}">  back to login</a>
</div> 
{% elif  userStatus == 3%}   
<div class="userStatus">
    Oops,Improper request
    <a href="{%url 'OTSapp:Registration'%}">back to Registration form</a>
</div> 
{%endif%}

{%endblock%}

OTSapp/templates/registration_form.html
{% extends 'main.html'%}

{% block tittle %}
OTS registration form
{% endblock %}

{% block top %} 

<a href="{%url 'OTSapp:login'%}">Login</a>
{%endblock%}

{% block content %}
<div class="all-form">
    <form action="{%url 'OTSapp:storeCandidate'%}" method="POST">
        {% csrf_token %}
        <label for ="username ">username</label>
        <input type="text"  name="username" id="username" placeholder="username" required>
        <label for ="password">password</label>
        <input type="password" name="password" id="password" placeholder="password" required>
        <label for= "name">Name </label>
        <input type="text" name="name" id="name" placeholder="name" required>

        <input type="submit" value="submit">
        <input type="reset" value="reset">
        
    </form>
    Already have an account? <a href="{%url 'OTSapp:login'%}">click here</a>
</div>
{%endblock%}

OTSapp/templates/show_result.html
{% extends 'main.html' %}

{% block tittle %}
Test Result
{% endblock %}

{% block top %} 
<a  href="{%url 'OTSapp:home'%}" style="color:red;">Home</a>
<br>
<br>
<a href="{%url 'OTSapp:logout'%}" style="color:green;">Login</a>
{%endblock%}

{% block content %}
<Table border="2px">
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>right</th>
        <th>wrong</th>
        <th>points</th>
    </tr>
    {% for r in result%}
    <tr>
        <td>{{r.date}}</td>
        <td>{{r.time}}</td>
        <td>{{r.attempt}}</td>
        <td>{{r.right}}</td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>

    </tr>
    {% endfor %}

</Table>
{%endblock%}
 
 

OTSapp/templates/test_paper.html
{% extends 'main.html ' %}

{%block tittle %}OTS- Test paper  {%endblock  %}

{%block top %}
{%endblock  %}

{%block content %}
<form action="{%url 'OTSapp:calculateTest' %}" method="post">
    {% csrf_token %}
    {% for question in questions %}
    <div class="question">
        <input type="hidden" name="qno{{question.qid}}" value="{{question.qid}}">
        {{question.que}}
    </div>

    <div class="options"><input type="radio" name="q{{question.qid}}"  value="a">{{question.a}}</div>
    <div class="options"><input type="radio" name="q{{question.qid}}"  value="b">{{question.b}}</div>
    <div class="options"><input type="radio" name="q{{question.qid}}"  value="c">{{question.c}}</div>
    <div class="options"><input type="radio" name="q{{question.qid}}"  value="d">{{question.d}}</div>
    {% endfor %}

    <div><input type="submit" value="submit"></div>
 

</form>
{%endblock %}

OTSapp/templates/welcome.html
{% extends 'main.html' %}

{% block tittle %}
Welcome to the Online Testing system
{% endblock %}

{% block top %} 
<a  href="{%url 'OTSapp:Registration'%}" style="color:red;">Sign up</a>
<br>
<br>
<a href="{%url 'OTSapp:login'%}" style="color:green;">Login</a>
{%endblock%}

{% block content %}
<p>Welcome to the Online Testing System</p>
{%endblock%}
 
 